### PR TITLE
Moved Kirby's copy ability scripts to another folder so that the view from the online repository wouldn't hide any of Kirby's scripts.

### PR DESCRIPTION
**Pull request by DeroPlayz**

### CODE REVIEW

**Review by WuBoytH — CHANGES_REQUESTED** [review]
Please ensure everything is moving to a singular folder, currently you have a `kirby_copy_abilities` and a `kirby_copy` folder

I would also ask you do the same with the `smashline-hdr` folder.

**Comment by DeroPlayz** [comment]
Gotcha!

**Comment by DeroPlayz** [comment]
Fixed HDR to also have a new folder for copy ability scripts & removed unused `kirby_copy_abilities` folder.

**Review by WuBoytH — DISMISSED** [review]

**Comment by WuBoytH** [comment]
It appears you made the smashline-hdr change on the `main` branch of your fork, please do that for the `kirby_fix` branch instead.

**Comment by WuBoytH** [comment]
Closed cause I ended up doing it myself

**Pull request closed without merging**
